apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-gateway.fullname" . }}
  labels:
    {{- include "vault-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vault-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
